### ISSUE TITLE
writeback works also by instruments set as readonly

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ReportTweaks#1]
First of all, thank you very much, finally a module how put everything on the same line!!
And in the same module you put also the writeback function. That's great.

Issue: Writeback function would insert data in instrument even if they are set as readonly for the user giving the cmd. By users without the write permission, that should not work.

**Comment by aanunez** [comment]
Thanks for the report Thomas. I'm testing fix for this now, will likely see a release next week.
