### ISSUE TITLE
link to instruction in readme file not working

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ReportTweaks#17]
Hi Adam,

I was trying to get to the instruction link, but it doesn't seem to be available:
https://aanunez.io/docs/report-tweaks/

cheers
Thomas

**Comment by aanunez** [comment]
Oof, the credit card I used for the domain expired. The site will be back up very soon. Sorry about that.

**Comment by colinaut** [comment]
Subscribing to this issue as I am curious to see the docs for this. Working on implementing a REDCap database and I'd definitely want to add a module that improves the Reports. Nice that this one uses DataTable which is pretty solid.

Note you could always use Github Pages to host your docs. That way it's in the same repo and no worries about linking to an external site.

**Comment by aanunez** [comment]
Going through older issues now on github. This was resolved a while ago, link works as expected now.
