### ISSUE TITLE
write data back overwrite date with empty value

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ReportTweaks#18]
Me again =)
I'm trying to overwrite with empty values all the dates that I have in my report. (which are in the past and no more usefull for our scenario)

![image](https://github.com/uwctri/ReportTweaks/assets/75424115/ba9d9700-3b01-435a-80a9-0b2a30548316)

EM says that the process was succesfull, but actually no change was done.

many thanks
Thomas

**Comment by aanunez** [comment]
Could you share the XML for the project or a simplified version of it?

**Comment by ThomasVermes** [comment]
[TweakReportWriteBack_ModuleSettingsExport_2024-01-15.zip](https://github.com/uwctri/ReportTweaks/files/13935927/TweakReportWriteBack_ModuleSettingsExport_2024-01-15.zip)

[TweakReportWriteBack_2024-01-15_0808.REDCap.zip](https://github.com/uwctri/ReportTweaks/files/13935944/TweakReportWriteBack_2024-01-15_0808.REDCap.zip)

In this simplified project I was not able to reproduce the same problem as above, but still I got this error:

![image](https://github.com/uwctri/ReportTweaks/assets/75424115/4a6be4df-91a0-41ca-918d-742705e8f0e4)
Then I wondering if it is on our side

**Comment by aanunez** [comment]
The issue may be that my code is rejecting the write value due to it being blank, but I have not been able to look into this yet to verify. I will hopefully be able to look further before the end of the week.

**Comment by aanunez** [comment]
@ThomasVermes were you able to confirm if this was a real issue or a problem on your side? I'm going though issues and I just wanted to ask for input before I looked into this.

**Comment by ThomasVermes** [comment]
dear Adam, Yeah it still an issue. To replicate it should be quite quick. Instal the xml project, go on the report (there is just one) and click and "Delete date".

**Comment by aanunez** [comment]
Just resolved this in a recent commit. Plan to do a release today or tomorrow.
