### ISSUE TITLE
Request: Report description, a button to collapse it

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ReportTweaks#19]
Just some wishes which could be nice to have:

Like for the report filters, it would be nice to have a button which collapse (i.e. https://getbootstrap.com/docs/5.3/components/collapse/ ) the report description (sometime can be really long).

one checkbox in the report' setting for having this button displayed below the report's title and another checkbox for having the report description collapsed by default.
best
Thomas

**Comment by aanunez** [comment]
Adding this as an option in next release

**Comment by aanunez** [comment]
Closing now. New release was submitted to Vanderbilt today. Will likely be available Monday or Tuesday.
