### ISSUE TITLE
Writeback with more variables

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ReportTweaks#2]
Would be even more interesting if it would be possible to change even more variables using the write back =)

**Comment by aanunez** [comment]
This has been implemented and tested over the past few weeks. We can now add multiple writeback buttons to a single report. Its won't be a documented feature (yet) but you can now also writeback to multiple fields with different values using the same button by naming additional buttons "^". This is a workaround until a I implement a better UI as I needed the functionality. 

I will submit the new version to Vanderbilt soon and it should be live
