### ISSUE TITLE
gzuncompress expecting a string, not array

### ISSUE THREAD

**Issue by aanunez** [uwctri/ReportTweaks#20]
Reported by @jgardner-qha

REDCap 14.2.2 · PHP 8.2.15 (Linux/Unix OS) · MariaDB 11.0.4

I don't know if it's just me, but I get this error on the latest version, apparently related to the gzip functionality.
Based on line 178, I'm guessing that an assumption is made - if the gzuncompress function returns anything other than false, it returns the result, otherwise it leaves the original value. However, line 176 seems to build an array, but gzuncompress only works with strings. Should the "gzuncompress" function instead be called for each element of the array?

`The 'report_tweaks' module threw the following exception when calling the hook method 'redcap_every_page_top':

TypeError: gzuncompress(): Argument https://github.com/uwctri/ReportTweaks/issues/1 ($data) must be of type string, array given in /redcap/modules/report_tweaks_v1.2.6/ReportTweaks.php:178`

**Comment by aanunez** [comment]
There were fundamental issues with decoding/decompressing the json array in settings. Not sure how this made it by my testing, I have to assume that I mistakenly undid changes that I planned to commit. I have resolved the issue now and re-tested.

**Comment by jgardner-qha** [comment]
Thank you! I appreciate you. This module has become a staple on many of our REDCap projects.
