### ISSUE TITLE
Setting issue: not able to change setting of a new report

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ReportTweaks#21]
Hello Adam,
I think something is still to be fixed regarding the setting.

If a report has existing settings, in version 1.2.7 it is possible to change them.
(Report and EM settings were initially created in version 1.2.5)

However, if it is a brand new report where EM setting are not yet save (in this redcap table: select * from redcap_external_module_settings), it is not possible set up (new) EM settings.

Can you replicate the problem?
(we are in redcap version 14.3.1 if it might be relevant)

**Comment by aanunez** [comment]
Hey Thomas,

I'm not able to duplicate this issue. If you go to the EM's configuration and click the "Click here to view all saved configuration." text you will be able to see the JSON object that stores all configuration for the EM. Could you copy paste that JSON into an online editor (https://jsonformatter.org/) and check for issues? 

Other questions I have:

* Do you have a very large number of reports? Over 400?
* This issue **Only** occurs for existing projects that have new reports added, but isn't an issue for reports in new projects?
* Are any errors reported in the JS console when saving or viewing the report?

Hopefully we can get this issue resolved quickly.

**Comment by aanunez** [comment]
Hey again. I just looked into this and I might have found the issue. We can only save settings to reports that already exist, so for reports that haven't been saved for the first time yet we can't make any changes. At some point changes I made broke some JS that disabled the config area during inital report creation so it looked like settings could be changed, but it was never the case that they could be. I have corrected this issue in 1.2.8 which I've submitted to Vanderbilt today. If that doesn't sound like the same issue you are facing then let me know, or feel free to upgrade and test first.

Thanks.

**Comment by ThomasVermes** [comment]
it sounds exactly like my issue =).
I let you know again when the EM is released!
thank you very much!!
Thomas

**Comment by aanunez** [comment]
Hey Thomas, was this issue resolved?

**Comment by ThomasVermes** [comment]
sorry i forgot to reply. Of cours it was fixed =)
Thank you very much!!!
