### ISSUE TITLE
Not working if ordering not by record_id

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ReportTweaks#3]
If I order my report from another variable which is not record_id, rows are not put together
![image](https://user-images.githubusercontent.com/75424115/147572136-f175ddde-b5c8-464a-87e2-b5bc504d045a.png)

**Comment by aanunez** [comment]
I'm about to push a fix for this. Like the other bug report these should be live next week in v1.1.1

**Comment by ThomasVermes** [comment]
Hi Adam, here is me again =)
I've encountered a similar issue (the same), when working with more events.
When the EM Option "combine rows" is activate and, the report is not sorted correctly.
![image](https://user-images.githubusercontent.com/75424115/174966296-ad9808d2-c9ac-472b-b6e5-c097268411ca.png)
![image](https://user-images.githubusercontent.com/75424115/174966631-8798ba83-308f-4904-b924-85f55feb4eb6.png)

xml follow by email =)

**Comment by aanunez** [comment]
Hey Thomas. To clarify for me, I assume that the dates above are formatted as Day-Month-Year? In the US I have to deal with Month-Day-Year and Day-Month-Year so I wanted to be sure. Assuming that's correct it would appear I've incorrectly determined the date format somewhere.

**Comment by ThomasVermes** [comment]
Dear Adam,
sorry form y late reply.
Yes indeed, the date format is dd-mm-yyyy

Best regards
Thomas

**Comment by aanunez** [comment]
I've released a fix for this issue that will hopefully be available tomorrow (pending Vanderbilt approval).

**Comment by ThomasVermes** [comment]
Hi Adam, it looks like it works =). Thank you very much. I'll keep you update if I see other issue!
best Thomas

**Comment by aanunez** [comment]
Thanks for the confirmation Thomas. Closing the issue.
