### ISSUE TITLE
V1.1.1 Not working

### ISSUE THREAD

**Issue by ThomasVermes** [uwctri/ReportTweaks#4]
Hello Adam,
thank very much to taking into account our issues,
we are now on version 1.1.1 and unfortunately it doesnt work any more..
I can't understand if it is up to us or the module.

thanks for helping
![image](https://user-images.githubusercontent.com/75424115/148514097-f42d21ea-921c-43e2-980d-3df6ebfc201f.png)

![image](https://user-images.githubusercontent.com/75424115/148514351-0650ae76-5940-4cb7-81b6-4865ee6c52b6.png)

**Comment by aanunez** [comment]
Would you mind hitting "Ctrl + Shift + J" to open developer console and reporting any errors you see there? If you don't see any issues do you think you could upload the project XML so I could take a look?

**Comment by ThomasVermes** [comment]
Dear Adam,
unfortunately I cannot share the XML for this exact project, but maybe I can replicate the error in another project.
here below the warnin email we got:
I hope it can also help!
thanks
Thomas

The 'report_tweaks' module threw the following exception when calling the hook method 'redcap_every_page_top':

Exception: An error occurred while running an External Module query: 'Statement preparation failed'. The error from the database was: 'Unknown database 'ctriredcap''. See the server error log for more details. in D:\Data\htdocs\redcap_v12.0.7\ExternalModules\classes\ExternalModules.php:2613
Stack trace:
#0 D:\Data\htdocs\redcap_v12.0.7\ExternalModules\classes\framework\Framework.php(2515): ExternalModules\ExternalModules::query()
#1 [internal function]: ExternalModules\Framework->query()
#2 D:\Data\htdocs\redcap_v12.0.7\ExternalModules\classes\framework\Framework.php(265): call_user_func_array()
#3 D:\Data\htdocs\redcap_v12.0.7\ExternalModules\classes\AbstractExternalModule.php(87): ExternalModules\Framework->callFromModuleInstance()
#4 D:\Data\htdocs\redcap_v12.0.7\ExternalModules\classes\AbstractExternalModule.php(186): ExternalModules\AbstractExternalModule->__call()
#5 D:\Data\htdocs\modules\report_tweaks_v1.1.1\ReportTweaks.php(173): ExternalModules\AbstractExternalModule->query()
#6 D:\Data\htdocs\modules\report_tweaks_v1.1.1\ReportTweaks.php(34): UWMadison\ReportTweaks\ReportTweaks->loadReportSorting()
#7 D:\Data\htdocs\redcap_v12.0.7\ExternalModules\classes\ExternalModules.php(2877): UWMadison\ReportTweaks\ReportTweaks->redcap_every_page_top()
#8 D:\Data\htdocs\redcap_v12.0.7\ExternalModules\classes\ExternalModules.php(3005): ExternalModules\ExternalModules::startHook()
#9 D:\Data\htdocs\redcap_v12.0.7\ExternalModules\classes\ExternalModules.php(3038): ExternalModules\ExternalModules::ExternalModules\{closure}()
#10 D:\Data\htdocs\redcap_v12.0.7\Classes\Hooks.php(42): ExternalModules\ExternalModules::callHook()
#11 D:\Data\htdocs\redcap_v12.0.7\Classes\HtmlPage.php(127): Hooks::call()
#12 D:\Data\htdocs\redcap_v12.0.7\Views\HeaderProject.php(29): HtmlPage->PrintHeader()
#13 D:\Data\htdocs\redcap_v12.0.7\ProjectGeneral\header.php(4): require('D:\\Data\\htdocs\\...')
#14 D:\Data\htdocs\redcap_v12.0.7\DataExport\index.php(96): include('D:\\Data\\htdocs\\...')
#15 {main}

URL: https://fxdb.usb.ch/redcap_v12.0.7/DataExport/index.php?pid=1231&report_id=2813
Server: fxdb.usb.ch (ictredcapwp01)
User: vermest
Project ID: 1231
Module Name: Report Tweaks (report_tweaks)
Module Author(s): Adam.Nunez@ctri.wisc.edu
Run Time: 0 seconds

**Comment by aanunez** [comment]
I just pushed a fix for this, thank you for sharing the email. The issue was introduced when I referenced the exact name of my servers DB. I will be making a 1.1.2 release to correct this single bug.
