### ISSUE TITLE
Date range live filter setting field not loaded properly

### ISSUE THREAD

**Issue by jgardner-qha** [uwctri/ReportTweaks#7]
REDCap v12.5.9 PHP 7.4
ReportTweaks 1.2.0

Summary:
When the Edit Report screen is loaded, the module does not correctly populate the Report Tweaks setting for the date range live filter.

Steps to reproduce:
1. Create a report and save the report to get a report_id.
2. Change the date range live filter field to an appropriate date field.
3. Save the report.
4. Run the report and test the date range live filter; it seems to work correctly.
5. Run a query on the database to see that the correct value for dateField is identified in the settings json string. I use, for example: `select * from redcap_external_module_settings where external_module_id = 15 and project_id = 21`
6. Edit the report.
7. Notice that the date range live filter drop-down is incorrectly populated.
8. Save the report without changing anything.
9. Run the query on the database to see that now the incorrect value for dateField is identified in the settings json string.

The effect is that every time a report is edited, the date range live filter needs to be selected again, otherwise the report will not function as desired.

**Comment by aanunez** [comment]
Closing this now as it has been resolved via the above referenced commit. A release should be available from Vanderbilt early next week.
